features_multimodal = [
    "Sex",
    "Age",
    "Pain",
    "Neoplasm history",
    "Number of lesions",
    "Expandability",  # -> "Progression"
    "Bone type",
    "Longitudinal location",
    "Lytic bone lesion",
    "Lytic bone lesion matrix",
    "Trabecular lytic bone lesion",
    "Sclerotic bone lesion",
    "Mixed bone lesion",
    "MRI matrix",
    "Endosteal scalloping",
    "Cortical lysis",
    "Pathologic fracture",
    "MRI perilesional bone marrow edema",
    "MRI fatty halo",
    "MRI skip metastasis",
    "Do not touch",
    "General symptoms",
    "Anatomical region",
    "Size (mm)",
    "Transversal location",
    "Shape",
    "MRI contrast enhancement",
    "Lodwick-Madewell",
    "Periosteal reaction",
    "MRI soft tissue invasion",
    "Suspicion for metastases",
]

features_rx = [
    "Sex",
    "Age",
    "Pain",
    "Neoplasm history",
    "Number of lesions",
    "Expandability",
    "Bone type",
    "Longitudinal location",
    "Lytic bone lesion",
    "Lytic bone lesion matrix",
    "Trabecular lytic bone lesion",
    "Sclerotic bone lesion",
    "Mixed bone lesion",
    "Endosteal scalloping",
    "Cortical lysis",
    "Pathologic fracture",
    "Do not touch",
    "General symptoms",
    "Anatomical region",
    "Size (mm)",
    "Transversal location",
    "Shape",
    "Lodwick-Madewell",
    "Periosteal reaction",
    "Suspicion for metastases",
]

features_mr = [
    "Sex",
    "Age",
    "Pain",
    "Neoplasm history",
    "Number of lesions",
    "Expandability",
    "Bone type",
    "Longitudinal location",
    "MRI matrix",
    "MRI perilesional bone marrow edema",
    "MRI fatty halo",
    "MRI skip metastasis",
    "Do not touch",
    "General symptoms",
    "Anatomical region",
    "Size (mm)",
    "Transversal location",
    "Shape",
    "MRI contrast enhancement",
    "MRI soft tissue invasion",
    "Suspicion for metastases",
]

features_numeric = ["Age", "Size (mm)"]

feature_names_printed = {
    "Shape_irregular": "Irregular shape",
    "Shape_round/oval": "Round/oval shape",
    "Shape_lobulated": "Lobulated shape",
    "Lodwick-Madewell_grade I": "Tumor margins Lodwick Madewell type I",
    "Lodwick-Madewell_grade III": "Tumor margins Lodwick Madewell type III",
    "Size (mm)": "Size",
    "Periosteal reaction_aggressive": "Aggressive periosteal reaction",
    "Periosteal reaction_non-aggressive": "Non-aggressive periosteal reaction",
    "Periosteal reaction_absence": "Absence of periosteal reaction",
    "MRI soft tissue invasion_absence": "Absence of soft tissue invasion",
    "MRI soft tissue invasion_presence": "Soft tissue invasion",
    "Anatomical region_axial (spine/pelvis)": "Spine/pelvis region",
    "Anatomical region_body walls": "Body walls",
    "Suspicion for metastases_presence": "Suspected metastatic disease",
    "Suspicion for metastases_not applicable": "Suspected metastatic disease NA",
    "Bone type_flat bone": "Flat bone",
    "Bone type_hand/foot": "Hand or foot bones",
    "Cortical lysis_absence": "Absence of cortical lysis",
    "Cortical lysis_presence": "Cortical lysis",
    "Neoplasm history_presence": "History of neoplasm",
    "Trabecular lytic bone lesion_coarse/disorganized trabeculation": "Gross/disorganized internal trabecular pattern",
    "MRI contrast enhancement_absence": "Absence of MRI contrast enhancement",
    "Mixed bone lesion_presence": "Mixed bone lesion",
    "Sclerotic bone lesion_presence": "Sclerotic bone lesion",
    "MRI perilesional bone marrow edema_absence": "Absence of perilesional bone marrow oedema",
    "Do not touch_presence": "Presumed imaging diagnosis (Do not touch lesion)",
    "Expandability_presence": "Progression",
    "Expandability_absence": "Absence of Progression",
    "Expandability_not applicable": "Progression first visit",
    "Pain_absence": "Absence of pain",
    "MRI matrix_fibrous": "Fibrous matrix",
    "Transversal location_subperiosteal": "Subperiosteal location",
    "MRI matrix_liquid without liquid-liquid levels": "Fluid without fluid-fluid levels",
    "Number of lesions_multiples": "Multiple lesions",
}
